FLASK_APP=main.py
FLASK_ENV=development
FLASK_DEBUG=true
FLASK_RUN_PORT=6969
GAE_ENV=development
GOOGLE_APPLICATION_CREDENTIALS=C:\Users\JANGARITA.SERVINF\Documents\PROYECTOS\EMONEY\BackEndBase\service-account.json
