# -*- coding: utf-8 -*-

"""
local settings for Cl4ptr4p project.
Generated by 'Cl4ptr4p startproject' using Flask 0.12.2.

For more information on this file, see
README.md
"""

APP_PATH = 'app'
LIB_PATH = 'lib'

ENDPOINT_API = '/api'
HEADER_API_KEY = 'Authorization'
TOKEN_TYPE = 'Bearer'

SESSION_EXPIRE_TIME = 14400  # 4 hours

ALLOW_METHODS = "GET, POST, PUT, DELETE, OPTIONS, PATCH"

# server configurations
DEFAULT_HOST = '0.0.0.0'
DEFAULT_PORT = 6969
DEBUG = True
ACTIVATE_ENV = False
USE_STDERR = True

# Internationalization
TIME_ZONE = 'UTC -5'
STDR_UTC_HOUR = 5
LOCAL_UTC_HOUR = -5

LANGUAGE_CODE = 'en-us'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Url proyecto crypto

CRYPTO_PROJECT = {
        "TOKEN": "https://cripto-dot-george-projects.appspot.com/api/bit/token/KEY_test_741258369",
        "BITCOIN": "https://cripto-dot-george-projects.appspot.com/api/bit/cop_value",
        "LITECOIN": "https://cripto-dot-george-projects.appspot.com/api/lite/cop_value",
        "DOGECOIN": "https://cripto-dot-george-projects.appspot.com/api/doge/cop_value",
        "TRANSATION_BITCOIN": "https://cripto-dot-george-projects.appspot.com/api/bit/send_transaction",
        "TRANSATION_LITECOIN": "https://cripto-dot-george-projects.appspot.com/api/lite/send_transaction",
        "TRANSATION_DOGECOIN": "https://cripto-dot-george-projects.appspot.com/api/doge/send_transaction",
        "BALANCE_BITCOIN": "https://cripto-dot-george-projects.appspot.com/api/bit/get_balance/",
        "BALANCE_LITECOIN": "https://cripto-dot-george-projects.appspot.com/api/lite/get_balance/",
        "BALANCE_DOGECOIN": "https://cripto-dot-george-projects.appspot.com/api/doge/get_balance/"         
}