class AuthProfiles(object):
    """docstring for AuthProfiles"""
    IS_ACTIVE = 11
    ACTIVE = 'Active'
    INACTIVE = 'Inactive'
    BANNED = 'Banned'

    GOTU = 'GOD_OF_THE_UNIVERSE'
    SUPER_ADMIN = 'SUPER_ADMIN'
    GENERAL_ADMINISTRATOR = 'GENERAL_ADMINISTRATOR'
    COMPANY_OWNER = 'COMPANY_OWNER'
    APPS_ADMINISTRATOR = 'APPS_ADMINISTRATOR'
    USER_OPERATIONAL = 'USER_OPERATIONAL'
    USERS_ADMINISTRATOR = 'USERS_ADMINISTRATOR'
    REGULAR_USER = 'REGULAR_USER'
    ANONYMOUS_USER = 'ANONYMOUS_USER'

    # Primitive Roles'
    ROLES = ['GOTU', 'SUPER_ADMIN', 'GENERAL_ADMINISTRATOR', 'REGULAR_USER', 'USER_OPERATIONAL', 'GUEST']
